### ISSUE TITLE
NoMethodError: undefined method `mock_model'

### ISSUE THREAD

**Issue by ghost** [geermc4/spree_user_groups#4]
I'm updating this to work with 2.4, but I'm unfamiliar with rspec - any ideas why "mock_model" is not working here?

```
NoMethodError: undefined method `mock_model' for #<RSpec::ExampleGroups::SpreeCalculatorAdvancedFlatPercentBasedOnMasterPrice::Compute:0x007fdaf520d230>
./spec/models/calculator/advanced_flat_percent_spec.rb:5:in `block (2 levels) in <top (required)>'
./spec/models/calculator/advanced_flat_percent_spec.rb:11:in `block (3 levels) in <top (required)>'
```

``` ruby
describe 'Spree::Calculator::AdvancedFlatPercent based on master_price' do
  let(:calculator) { Spree::Calculator::AdvancedFlatPercent.new }
  let(:order) { mock_model Spree::Order, :line_items => [mock_model(Spree::LineItem, :amount => 10), mock_model(Spree::LineItem, :amount => 20)], :user => mock_model(Spree::User) }

  before { calculator.stub :preferred_flat_percent => 10, :preferred_based_on_cost_price => false }

  context "compute" do
    it "should compute amount correctly" do
      calculator.compute(order).should == -3.0
    end

    it "should round result correctly" do
      order.stub :line_items => [mock_model(Spree::LineItem, :amount => 10.56), mock_model(Spree::LineItem, :amount => 20.49)]
      calculator.compute(order).should == -3.11

      order.stub :line_items => [mock_model(Spree::LineItem, :amount => 10.56), mock_model(Spree::LineItem, :amount => 20.48)]
      calculator.compute(order).should == -3.10
    end
  end
end
```

I've tried adding "rspec-activemodel-mocks" since I saw they were trying to move these mocks out of rspec-rails, but this didn't help.

Thank you,
Bryan

**Comment by geermc4** [comment]
:anguished: no idea sorry.

**Comment by ghost** [comment]
Ok, solved, now that **rspec-rails** has moved _stub_model_ & _mock_model_ out to [rspec-activemodel-mocks](https://github.com/rspec/rspec-activemodel-mocks), you need to add the following to your spec_helper.rb:

```
require 'rspec/active_model/mocks'
```

I'm new to submitted patches back to their respective authors, but I'll try to do a pull request back to you with my 2-4-stable branch and respective test fixes.
